### ISSUE TITLE
Check if subCategories is null

### ISSUE THREAD

**Issue by bghull** [hoostus/beancount-ynab#5]
This might be an edge case since my production budget is years old and has undergone several major changes, but my Budget.yfull has two masterCategories where subCategories is null:
```
{
	"entityType": "masterCategory",
	"expanded": true,
	"name": "New Master Category",
	"type": "OUTFLOW",
	"deleteable": true,
	"subCategories": null,
	"isTombstone": true,
	"entityVersion": "A-282",
	"entityId": "5ADFC5F6-B872-385F-3508-75CBA92A4703",
	"sortableIndex": 268435455
},
{
	"entityType": "masterCategory",
	"expanded": true,
	"name": "Income",
	"type": "INFLOW",
	"deleteable": false,
	"subCategories": null,
	"entityVersion": "H-1533",
	"entityId": "MasterCategory/__Income__",
	"sortableIndex": 1073741823
},
```
This causes `get_categories()` to fail unless a check is inserted before calling `entity_dict(m['subCategories'])`.

**Comment by hoostus** [comment]
Thanks for these updates on the arcane corners of YNAB4's format. I'm not totally clear on what these are? Are they old & no longer used?

If so, we can just skip them (just like the 'isTombstone' check on the line above the one you reference). If that's all that's needed it is straightforward.

**Comment by bghull** [comment]
Honestly I'm not sure what these categories are either. This is an old (~2014) budget file so it might have some crusty old quirks from earlier releases of YNAB4. That simple fix is probably enough for these edge cases.

**Comment by hoostus** [comment]
I committed a small fix; let me know if it works for you.
